export const validActions = new Set<string>(['down', 'up', 'hold']);

export const validMouseEvents = new Set<string>([
    'click',
    'dblclick',
    // 'mousedown',
    // 'mouseup',
    // 'mousemove',
    // 'mouseenter',
    // 'mouseleave',
    // 'mouseover',
    // 'mouseout',
    // 'contextmenu',
]);

export const validTouchEvents = new Set<string>([
    // 'touchstart',
    // 'touchend',
    // 'touchmove',
    // 'touchcancel'
]);

export const validKeyCodes = new Set<string>([
    'Backspace',
    'Tab',
    'Enter',
    'Shift',
    'Control',
    'Alt',
    'Pause',
    'CapsLock',
    'Escape',
    'Space',
    'PageUp',
    'PageDown',
    'End',
    'Home',
    'ArrowLeft',
    'ArrowUp',
    'ArrowRight',
    'ArrowDown',
    'PrintScreen',
    'Insert',
    'Delete',
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    'F1',
    'F2',
    'F3',
    'F4',
    'F5',
    'F6',
    'F7',
    'F8',
    'F9',
    'F10',
    'F11',
    'F12',
    'NumLock',
    'ScrollLock',
    'Semicolon',
    'Equal',
    'Comma',
    'Minus',
    'Period',
    'Slash',
    'Backquote',
    'BracketLeft',
    'Backslash',
    'BracketRight',
    'Quote',
]);

export const supportedEvents = new Set([...validMouseEvents, ...validTouchEvents, ...validKeyCodes]);
